import sys
import os
import time

def NewSong():
    os.system('clear')
    print('A special treat from me to you on our everyday')
    print('Select from the options below')
    print('[1] It will rain \n[2] Anyone \n[3] Count on me')

name = 'baby'
song = NewSong()
songs = input('Input value: ')

if songs == "1" or songs == "It will rain":
    time.sleep(0.5)
    os.system('clear')
    print('This one\'s for you ' + name)
    time.sleep(2)
    os.system('clear')
    time.sleep(2)
    print("If you ever leave me " + name)
    time.sleep(3)
    print("Leave some morphines at my door")
    time.sleep(5)
    print("Cos it would take a whole lot of medications")
    time.sleep(7)
    print("To realize what we used to have we don't have it anymore")
    time.sleep(7)
    print("There's no religion that could save me")
    time.sleep(5)
    print("No matter how long my knees are on the floor, oh")
    time.sleep(6)
    print("So keep in mind all the sacrifices that I'm making")
    time.sleep(7)
    print("To keep you by my side")
    time.sleep(4)
    print("To keep you from walking out the door")
    time.sleep(7)
    print("Cos there'd be no sunlight")
    time.sleep(4)
    print("If I lose you " + name)
    time.sleep(4)
    print("There'd be no clear skies")
    time.sleep(3)
    print("If I lose you " + name)
    time.sleep(4)
    print("Just like the clouds, my eyes would do the same")
    time.sleep(7)
    print("If you walk away, every day it would rain")
    time.sleep(6)
    print("I'll never be your mother's favorite")
    time.sleep(4)
    print("Your dad can't even look me in the eyes")
    time.sleep(5)
    print("Well, if I was in their shoes I'd do the same thing")
    time.sleep(4)
    print("Say there goes my little girl walking with that troublesome guy")
    time.sleep(8)
    print("But they aren't just part of something they can understand")
    time.sleep(5)
    print("But little darling watch me change their minds")
    time.sleep(4)
    print("Yeah for you I'll try , I'll try, I'll try")
    time.sleep(5)
    print("I'll pick up the broken pieces till I'm bleeding if that would make it right")
    time.sleep(7)
    print("Cos there'd be no sunlight")
    time.sleep(4)
    print("If I lose you " + name)
    time.sleep(4)
    print("There'd be no clear skies")
    time.sleep(3)
    print("If I lose you " + name)
    time.sleep(4)
    print("Just like the clouds, my eyes would do the same")
    time.sleep(7)
    print("If you walk away, every day it would rain")
    time.sleep(6)
    dont = "Don't you say Goodbye"
    print(dont)
    time.sleep(4)
    print(dont)
    time.sleep(4)
    print("I'll pick up these broken pieces till I'm bleeding if that will make you mine")
    time.sleep(7)
    print("Cos there'd be no sunlight")
    time.sleep(4)
    print("If I lose you " + name)
    time.sleep(4)
    print("There'd be no clear skies")
    time.sleep(3)
    print("If I lose you " + name)
    time.sleep(4)
    print("Just like the clouds, my eyes would do the same")
    time.sleep(7)
    print("If you walk away, every day it would rain")
    time.sleep(3)
    print(song)